import numpy as np

ame43_G1_dict = {'Z⊗I⊗Z⊗Z': np.complex128(1-0j),
                 'I⊗I⊗I⊗I': np.complex128(1+0j)}

ame43_G1G2_dict = {'ZZ⊗ZZ⊗Z⊗I': np.complex128(1-0j),
                   'ZZ⊗ZI⊗I⊗Z': np.complex128(1-0j),
                   'ZZ⊗IZ⊗I⊗Z': np.complex128(1-0j),
                   'ZI⊗II⊗Z⊗Z': np.complex128(1-0j),
                   'IZ⊗II⊗Z⊗Z': np.complex128(1-0j),
                   'II⊗II⊗I⊗I': np.complex128(1+0j)}

ame43_G1G2pow2_dict = {'ZZZ⊗ZZZ⊗II⊗I': np.complex128(1-0j),
                       'ZZZ⊗ZZI⊗ZZ⊗Z': np.complex128(1-0j),
                       'ZZZ⊗ZIZ⊗ZZ⊗Z': np.complex128(1-0j),
                       'ZZZ⊗XXX⊗II⊗I': np.complex128(1-0j),
                       'ZZZ⊗IZZ⊗ZZ⊗Z': np.complex128(1-0j),
                       'ZZZ⊗III⊗II⊗I': np.complex128(1-0j),
                       'ZZI⊗ZZI⊗ZI⊗I': np.complex128(1-0j),
                       'ZZI⊗ZZI⊗IZ⊗I': np.complex128(1-0j),
                       'ZZI⊗ZIZ⊗ZI⊗I': np.complex128(1-0j),
                       'ZZI⊗ZIZ⊗IZ⊗I': np.complex128(1-0j),
                       'ZZI⊗ZII⊗II⊗Z': np.complex128(1-0j),
                       'ZZI⊗IZZ⊗ZI⊗I': np.complex128(1-0j),
                       'ZZI⊗IZZ⊗IZ⊗I': np.complex128(1-0j),
                       'ZZI⊗IZI⊗II⊗Z': np.complex128(1-0j),
                       'ZZI⊗IIZ⊗II⊗Z': np.complex128(1-0j),
                       'ZIZ⊗ZZI⊗ZI⊗I': np.complex128(1-0j),
                       'ZIZ⊗ZZI⊗IZ⊗I': np.complex128(1-0j),
                       'ZIZ⊗ZIZ⊗ZI⊗I': np.complex128(1-0j),
                       'ZIZ⊗ZIZ⊗IZ⊗I': np.complex128(1-0j),
                       'ZIZ⊗ZII⊗II⊗Z': np.complex128(1-0j),
                       'ZIZ⊗IZZ⊗ZI⊗I': np.complex128(1-0j),
                       'ZIZ⊗IZZ⊗IZ⊗I': np.complex128(1-0j),
                       'ZIZ⊗IZI⊗II⊗Z': np.complex128(1-0j),
                       'ZIZ⊗IIZ⊗II⊗Z': np.complex128(1-0j),
                       'ZII⊗ZZZ⊗ZI⊗Z': np.complex128(1-0j),
                       'ZII⊗ZZZ⊗IZ⊗Z': np.complex128(1-0j),
                       'ZII⊗ZII⊗ZZ⊗I': np.complex128(1-0j),
                       'ZII⊗XXX⊗ZI⊗Z': np.complex128(1-0j),
                       'ZII⊗XXX⊗IZ⊗Z': np.complex128(1-0j),
                       'ZII⊗IZI⊗ZZ⊗I': np.complex128(1-0j),
                       'ZII⊗IIZ⊗ZZ⊗I': np.complex128(1-0j),
                       'ZII⊗III⊗ZI⊗Z': np.complex128(1-0j),
                       'ZII⊗III⊗IZ⊗Z': np.complex128(1-0j),
                       'XXX⊗ZZZ⊗II⊗I': np.complex128(1-0j),
                       'XXX⊗ZZI⊗ZZ⊗Z': np.complex128(1-0j),
                       'XXX⊗ZIZ⊗ZZ⊗Z': np.complex128(1-0j),
                       'XXX⊗XXX⊗II⊗I': np.complex128(1+0j),
                       'XXX⊗IZZ⊗ZZ⊗Z': np.complex128(1-0j),
                       'XXX⊗III⊗II⊗I': np.complex128(1+0j),
                       'IZZ⊗ZZI⊗ZI⊗I': np.complex128(1-0j),
                       'IZZ⊗ZZI⊗IZ⊗I': np.complex128(1-0j),
                       'IZZ⊗ZIZ⊗ZI⊗I': np.complex128(1-0j),
                       'IZZ⊗ZIZ⊗IZ⊗I': np.complex128(1-0j),
                       'IZZ⊗ZII⊗II⊗Z': np.complex128(1-0j),
                       'IZZ⊗IZZ⊗ZI⊗I': np.complex128(1-0j),
                       'IZZ⊗IZZ⊗IZ⊗I': np.complex128(1-0j),
                       'IZZ⊗IZI⊗II⊗Z': np.complex128(1-0j),
                       'IZZ⊗IIZ⊗II⊗Z': np.complex128(1-0j),
                       'IZI⊗ZZZ⊗ZI⊗Z': np.complex128(1-0j),
                       'IZI⊗ZZZ⊗IZ⊗Z': np.complex128(1-0j),
                       'IZI⊗ZII⊗ZZ⊗I': np.complex128(1-0j),
                       'IZI⊗XXX⊗ZI⊗Z': np.complex128(1-0j),
                       'IZI⊗XXX⊗IZ⊗Z': np.complex128(1-0j),
                       'IZI⊗IZI⊗ZZ⊗I': np.complex128(1-0j),
                       'IZI⊗IIZ⊗ZZ⊗I': np.complex128(1-0j),
                       'IZI⊗III⊗ZI⊗Z': np.complex128(1-0j),
                       'IZI⊗III⊗IZ⊗Z': np.complex128(1-0j),
                       'IIZ⊗ZZZ⊗ZI⊗Z': np.complex128(1-0j),
                       'IIZ⊗ZZZ⊗IZ⊗Z': np.complex128(1-0j),
                       'IIZ⊗ZII⊗ZZ⊗I': np.complex128(1-0j),
                       'IIZ⊗XXX⊗ZI⊗Z': np.complex128(1-0j),
                       'IIZ⊗XXX⊗IZ⊗Z': np.complex128(1-0j),
                       'IIZ⊗IZI⊗ZZ⊗I': np.complex128(1-0j),
                       'IIZ⊗IIZ⊗ZZ⊗I': np.complex128(1-0j),
                       'IIZ⊗III⊗ZI⊗Z': np.complex128(1-0j),
                       'IIZ⊗III⊗IZ⊗Z': np.complex128(1-0j),
                       'III⊗ZZZ⊗II⊗I': np.complex128(1-0j),
                       'III⊗ZZI⊗ZZ⊗Z': np.complex128(1-0j),
                       'III⊗ZIZ⊗ZZ⊗Z': np.complex128(1-0j),
                       'III⊗XXX⊗II⊗I': np.complex128(1+0j),
                       'III⊗IZZ⊗ZZ⊗Z': np.complex128(1-0j),
                       'III⊗III⊗II⊗I': np.complex128(1+0j)}

ame43_G3_dict = {'Z⊗I⊗Z⊗ZI': np.complex128(1-0j),
                 'Z⊗I⊗Z⊗IZ': np.complex128(1-0j),
                 'I⊗Z⊗Z⊗ZZ': np.complex128(1-0j),
                 'I⊗I⊗I⊗II': np.complex128(1+0j)}

ame43_G1G4_dict = {'ZZ⊗Z⊗II⊗ZI': np.complex128(1-0j),
                   'ZZ⊗Z⊗II⊗IZ': np.complex128(1-0j),
                   'ZZ⊗I⊗ZZ⊗ZZ': np.complex128(1-0j),
                   'ZI⊗Z⊗ZZ⊗II': np.complex128(1-0j),
                   'ZI⊗I⊗ZI⊗ZI': np.complex128(1-0j),
                   'ZI⊗I⊗ZI⊗IZ': np.complex128(1-0j),
                   'ZI⊗I⊗IZ⊗ZI': np.complex128(1-0j),
                   'ZI⊗I⊗IZ⊗IZ': np.complex128(1-0j),
                   'IZ⊗Z⊗ZZ⊗II': np.complex128(1-0j),
                   'IZ⊗I⊗ZI⊗ZI': np.complex128(1-0j),
                   'IZ⊗I⊗ZI⊗IZ': np.complex128(1-0j),
                   'IZ⊗I⊗IZ⊗ZI': np.complex128(1-0j),
                   'IZ⊗I⊗IZ⊗IZ': np.complex128(1-0j),
                   'II⊗Z⊗ZI⊗ZZ': np.complex128(1-0j),
                   'II⊗Z⊗IZ⊗ZZ': np.complex128(1-0j),
                   'II⊗I⊗II⊗II': np.complex128(1+0j)}

ghz_raw_dict = {'ZZX': 1.0,
                'XIZ': 1.0,
                'IXZ': 1.0,
                'III': 1.0}

ghz_dict = {'ZZZ': 1.0,
            'XXX': 1.0,
            'III': 1.0}

